#!/usr/bin/env bash
# pursue-helper · one-command setup for volunteers
#
# Usage:
#   curl -fsSL https://rizzleroc.github.io/pursue-console/install-helper.sh | bash
#
# What it does:
#   1. Sparse-checkout only the directories a helper actually needs from
#      pursue-console (about 10 MB instead of the full 1 GB+ corpus + ORT
#      WASM that the deployed app ships).
#   2. Installs the daemon (npm install --prefix pursue-vision-mcp).
#   3. Leaves you with two commands to run:
#        npm start --prefix pursue-vision-mcp
#        npm run volunteer -- --my-handle=YOU
#
# Safety: this script does not require sudo. It only touches:
#   - ./pursue-helper/        (created in your current directory)
#   - ~/.pursue-vision-token  (generated by the daemon on first run)

set -euo pipefail

REPO="${PURSUE_HELPER_REPO:-https://github.com/rizzleroc/pursue-console}"
DEST="${PURSUE_HELPER_DEST:-pursue-helper}"

echo "[helper] cloning lean checkout of $REPO into ./$DEST"
if [ -d "$DEST" ]; then
  echo "[helper] $DEST already exists. Pulling latest…"
  git -C "$DEST" pull --ff-only
else
  # Filter blobs, no checkout, then sparse-checkout the helper-relevant subset.
  git clone --filter=blob:none --no-checkout --depth=1 "$REPO" "$DEST"
  git -C "$DEST" sparse-checkout init --cone
  git -C "$DEST" sparse-checkout set \
    pursue-vision-mcp \
    scripts/volunteer.mjs \
    scripts/build-work-available.mjs \
    src/data/events.js \
    HOW-CAN-I-HELP.md \
    JUDGE-STANDARD.md \
    CONTRIBUTING-CORPUS.md \
    LICENSE \
    README.md
  git -C "$DEST" checkout main
fi

echo "[helper] installing daemon deps (this is the only npm install you need)"
( cd "$DEST/pursue-vision-mcp" && npm install --no-audit --no-fund )

# We also need a couple of dev-only modules the volunteer.mjs script imports
# (pdfjs-dist for rendering, @napi-rs/canvas for the canvas backend).
# Install them into pursue-vision-mcp so volunteer.mjs can find them.
( cd "$DEST/pursue-vision-mcp" && npm install --no-audit --no-fund pdfjs-dist@^5 @napi-rs/canvas@^1 )

cat <<EOF

[helper] done. next steps:

  cd $DEST
  npm start --prefix pursue-vision-mcp         # launches Chrome + daemon
  # in another terminal:
  node pursue-vision-mcp/../scripts/volunteer.mjs --my-handle=YOUR_GITHUB_HANDLE --slice=20

your contributions land in:  contributions/YOUR_GITHUB_HANDLE/
the daemon writes its token to: ~/.pursue-vision-token

read first if you want context:  $DEST/HOW-CAN-I-HELP.md
EOF
