import { useEffect, useState } from "react";

// Shared hook for reading public/coverage.json across views (CoverageGrid,
// CoverageView, LiveFeedView hero). Mirrors useCorpusStats: one in-flight
// fetch shared across consumers via a module-level cache, automatic
// revalidation every REVALIDATE_MS so an open tab catches the next build.
//
// Returns { coverage, error, reload } where coverage is the parsed
// coverage.json (keys: generatedAt, events, aggregate, byEvent) or null
// until the first fetch resolves.
//
// The data this serves is regenerated by `npm run build` via
// scripts/diagnose-coverage.mjs (wired into the chain alongside
// build-next-missing.mjs).

const REVALIDATE_MS = 60_000;

let _cache = null;
let _lastFetchedAt = 0;

function fetchCoverage(bust = false) {
  const url = `${import.meta.env.BASE_URL}coverage.json${bust ? `?t=${Date.now()}` : ""}`;
  return fetch(url, { cache: bust ? "reload" : "default" })
    .then(r => r.ok ? r.json() : Promise.reject(new Error(`HTTP ${r.status}`)))
    .catch(async err => {
      await new Promise(r => setTimeout(r, 800));
      const r2 = await fetch(url, { cache: "reload" });
      if (!r2.ok) throw err;
      return r2.json();
    });
}

function loadCoverage(bust = false) {
  const now = Date.now();
  const stale = now - _lastFetchedAt > REVALIDATE_MS;
  if (bust || !_cache || stale) {
    _lastFetchedAt = now;
    _cache = { promise: fetchCoverage(bust || stale), resolvedAt: null, value: null };
    _cache.promise.then(v => { _cache.value = v; _cache.resolvedAt = Date.now(); }).catch(() => {});
  }
  return _cache.promise;
}

export default function useCoverage() {
  const [coverage, setCoverage] = useState(_cache?.value ?? null);
  const [error, setError] = useState(null);

  async function reload(bust = true) {
    setError(null);
    try { setCoverage(await loadCoverage(bust)); }
    catch (e) { setError(e.message || String(e)); }
  }

  useEffect(() => {
    let cancelled = false;
    loadCoverage(false)
      .then(v => { if (!cancelled) setCoverage(v); })
      .catch(e => { if (!cancelled) setError(e.message); });
    const id = setInterval(
      () => loadCoverage(true).then(v => { if (!cancelled) setCoverage(v); }).catch(() => {}),
      REVALIDATE_MS
    );
    return () => { cancelled = true; clearInterval(id); };
  }, []);

  return { coverage, error, reload };
}
