import { useEffect, useState } from "react";

// Shared hook for reading public/next-missing.json — the prioritized queue
// of pages most in need of human transcription. Drives the LIVE-view
// Coverage Wall CTA ("Open the next missing page →") deep-link target.
//
// Returns { nextMissing, top, error, reload }:
//   nextMissing — the full parsed JSON { generatedAt, queue: [...] }
//   top         — convenience: queue[0] or null
//
// Regenerated by `npm run build` via scripts/build-next-missing.mjs.

const REVALIDATE_MS = 60_000;

let _cache = null;
let _lastFetchedAt = 0;

function fetchNextMissing(bust = false) {
  const url = `${import.meta.env.BASE_URL}next-missing.json${bust ? `?t=${Date.now()}` : ""}`;
  return fetch(url, { cache: bust ? "reload" : "default" })
    .then(r => r.ok ? r.json() : Promise.reject(new Error(`HTTP ${r.status}`)))
    .catch(async err => {
      await new Promise(r => setTimeout(r, 800));
      const r2 = await fetch(url, { cache: "reload" });
      if (!r2.ok) throw err;
      return r2.json();
    });
}

function loadNextMissing(bust = false) {
  const now = Date.now();
  const stale = now - _lastFetchedAt > REVALIDATE_MS;
  if (bust || !_cache || stale) {
    _lastFetchedAt = now;
    _cache = { promise: fetchNextMissing(bust || stale), resolvedAt: null, value: null };
    _cache.promise.then(v => { _cache.value = v; _cache.resolvedAt = Date.now(); }).catch(() => {});
  }
  return _cache.promise;
}

export default function useNextMissing() {
  const [nextMissing, setNextMissing] = useState(_cache?.value ?? null);
  const [error, setError] = useState(null);

  async function reload(bust = true) {
    setError(null);
    try { setNextMissing(await loadNextMissing(bust)); }
    catch (e) { setError(e.message || String(e)); }
  }

  useEffect(() => {
    let cancelled = false;
    loadNextMissing(false)
      .then(v => { if (!cancelled) setNextMissing(v); })
      .catch(e => { if (!cancelled) setError(e.message); });
    const id = setInterval(
      () => loadNextMissing(true).then(v => { if (!cancelled) setNextMissing(v); }).catch(() => {}),
      REVALIDATE_MS
    );
    return () => { cancelled = true; clearInterval(id); };
  }, []);

  return {
    nextMissing,
    top: nextMissing?.queue?.[0] || null,
    error,
    reload,
  };
}
