import { useEffect, useState } from "react";

// Shared hook for reading public/patterns.json — the text-mined corpus
// patterns (shape / behavior / sensor / entity / date). Powers the
// "Mined index" rail in the LIVE-view Coverage Wall and the entity-strip
// in DossierView.
//
// Returns { patterns, error, reload } where patterns is the full parsed
// JSON: { generatedAt, sourceDocs, byKind: { shape[], behavior[],
// sensor[], entity[], date[] } }.
//
// Regenerated by `npm run build` via scripts/build-patterns.mjs (already
// wired into the build chain).

const REVALIDATE_MS = 60_000;

let _cache = null;
let _lastFetchedAt = 0;

function fetchPatterns(bust = false) {
  const url = `${import.meta.env.BASE_URL}patterns.json${bust ? `?t=${Date.now()}` : ""}`;
  return fetch(url, { cache: bust ? "reload" : "default" })
    .then(r => r.ok ? r.json() : Promise.reject(new Error(`HTTP ${r.status}`)))
    .catch(async err => {
      await new Promise(r => setTimeout(r, 800));
      const r2 = await fetch(url, { cache: "reload" });
      if (!r2.ok) throw err;
      return r2.json();
    });
}

function loadPatterns(bust = false) {
  const now = Date.now();
  const stale = now - _lastFetchedAt > REVALIDATE_MS;
  if (bust || !_cache || stale) {
    _lastFetchedAt = now;
    _cache = { promise: fetchPatterns(bust || stale), resolvedAt: null, value: null };
    _cache.promise.then(v => { _cache.value = v; _cache.resolvedAt = Date.now(); }).catch(() => {});
  }
  return _cache.promise;
}

export default function usePatterns() {
  const [patterns, setPatterns] = useState(_cache?.value ?? null);
  const [error, setError] = useState(null);

  async function reload(bust = true) {
    setError(null);
    try { setPatterns(await loadPatterns(bust)); }
    catch (e) { setError(e.message || String(e)); }
  }

  useEffect(() => {
    let cancelled = false;
    loadPatterns(false)
      .then(v => { if (!cancelled) setPatterns(v); })
      .catch(e => { if (!cancelled) setError(e.message); });
    const id = setInterval(
      () => loadPatterns(true).then(v => { if (!cancelled) setPatterns(v); }).catch(() => {}),
      REVALIDATE_MS
    );
    return () => { cancelled = true; clearInterval(id); };
  }, []);

  return { patterns, error, reload };
}
