import React, { useEffect, useMemo, useState } from "react";
import { EVENTS, AGENCY_COLORS } from "../data/events.js";
import { GlitchText, RadarSweep, flagBg } from "../components/Primitives.jsx";

// LIVE FEED — chronological stream of pages transcribed.
// Updates whenever public/live-feed.json is regenerated by
// scripts/build-live-feed.mjs (runs after every vision-ocr batch + on
// `npm run build`). The deployment is the source of truth; clones run
// the same script locally and PR their .vision-cache to contribute back.

const TIME_AGO = (ts) => {
  const s = Math.max(0, (Date.now() - ts) / 1000);
  if (s < 60) return `${Math.round(s)}s`;
  if (s < 3600) return `${Math.round(s/60)}m`;
  if (s < 86400) return `${Math.round(s/3600)}h`;
  return `${Math.round(s/86400)}d`;
};

const SOURCE_BADGE = {
  vision: { label: "VISION", color: "#82B6FF", note: "ChatGPT-vision transcription (high quality)" },
  ocr:    { label: "OCR",    color: "#FFD93D", note: "tesseract OCR (noisier, awaiting vision pass)" },
};

const eventById = Object.fromEntries(EVENTS.map(e => [e.id, e]));

export default function LiveFeedView({ onSelect }) {
  const [feed, setFeed] = useState(null);
  const [error, setError] = useState(null);
  const [filter, setFilter] = useState("all");  // "all" | "vision" | "ocr"
  const [reloadAt, setReloadAt] = useState(Date.now());

  useEffect(() => {
    setFeed(null); setError(null);
    fetch(`${import.meta.env.BASE_URL}live-feed.json?t=${reloadAt}`)
      .then(r => r.ok ? r.json() : Promise.reject(new Error(`HTTP ${r.status}`)))
      .then(setFeed)
      .catch(e => setError(e.message));
  }, [reloadAt]);

  const entries = useMemo(() => {
    if (!feed) return [];
    return feed.entries.filter(e => filter === "all" || e.source === filter);
  }, [feed, filter]);

  const stats = feed?.stats;

  return (
    <div className="px-3 sm:px-8 py-6">
      <div className="flex items-baseline justify-between mb-4 flex-wrap gap-2">
        <div className="flex items-center gap-3">
          <h2 className="font-mono text-emerald-300 text-lg sm:text-2xl tracking-[0.2em]">
            <GlitchText>┃ LIVE FEED</GlitchText>
          </h2>
          <span className="relative flex h-2 w-2">
            <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75"></span>
            <span className="relative inline-flex rounded-full h-2 w-2 bg-emerald-400"></span>
          </span>
        </div>
        <div className="font-mono text-[10px] text-emerald-700 flex items-center gap-3">
          {feed && <span>{feed.entries.length} transcriptions · gen {feed.generatedAt?.slice(0,16).replace("T"," ")}</span>}
          <button onClick={() => setReloadAt(Date.now())}
            className="px-2 py-0.5 rounded-sm border border-emerald-700/50 hover:border-amber-400 hover:text-amber-300 transition-colors tracking-widest">
            ↻ REFRESH
          </button>
        </div>
      </div>

      {/* Stats strip */}
      {stats && (
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-4 border border-emerald-700/40 bg-black/40 rounded-sm p-3 font-mono text-[11px]">
          <div>
            <div className="text-[9px] text-emerald-700 tracking-widest">TOTAL PAGES</div>
            <div className="text-emerald-200 text-base">{stats.totalPages.toLocaleString()}</div>
            <div className="text-[9px] text-emerald-600">across the corpus</div>
          </div>
          <div>
            <div className="text-[9px] text-emerald-700 tracking-widest">VISION</div>
            <div className="text-[#82B6FF] text-base">{stats.bySource.vision?.toLocaleString() || 0}</div>
            <div className="text-[9px] text-emerald-600">ChatGPT-transcribed</div>
          </div>
          <div>
            <div className="text-[9px] text-emerald-700 tracking-widest">TESSERACT</div>
            <div className="text-amber-300 text-base">{stats.bySource.ocr?.toLocaleString() || 0}</div>
            <div className="text-[9px] text-emerald-600">awaiting vision re-pass</div>
          </div>
          <div>
            <div className="text-[9px] text-emerald-700 tracking-widest">CHARACTERS</div>
            <div className="text-emerald-200 text-base">{(stats.totalChars/1000).toFixed(0)}K</div>
            <div className="text-[9px] text-emerald-600">indexed text</div>
          </div>
        </div>
      )}

      {/* Filter */}
      <div className="flex flex-wrap gap-2 mb-3">
        {["all", "vision", "ocr"].map(f => (
          <button key={f} onClick={() => setFilter(f)}
            className={`px-3 py-1 rounded-sm border font-mono text-[10px] tracking-widest transition-all ${
              filter === f ? "border-amber-400/80 text-amber-300 bg-amber-400/10"
              : "border-emerald-700/40 text-emerald-400 hover:border-emerald-500/70"}`}>
            {f === "all" ? "ALL" : f === "vision" ? "VISION ONLY" : "TESSERACT ONLY"}
            <span className="ml-1 opacity-50">({f==="all" ? feed?.entries.length || 0 : (stats?.bySource[f] || 0)})</span>
          </button>
        ))}
        <a href="https://github.com/rizzleroc/pursue-console/blob/main/CONTRIBUTING-CORPUS.md" target="_blank" rel="noopener noreferrer"
          className="ml-auto px-3 py-1 rounded-sm border border-amber-400/50 text-amber-300 hover:text-amber-100 hover:bg-amber-400/10 font-mono text-[10px] tracking-widest">
          ＋ CONTRIBUTE TRANSCRIPTIONS
        </a>
      </div>

      {error && (
        <div className="border border-rose-400/40 bg-rose-400/5 rounded-sm p-3 font-mono text-[11px] text-rose-300">
          ⊘ {error}
        </div>
      )}

      {!feed && !error && (
        <div className="font-mono text-[11px] text-emerald-700 py-12 text-center">◌ loading feed…</div>
      )}

      {feed && (
        <div className="border border-emerald-700/40 bg-black/40 rounded-sm overflow-hidden relative">
          <div className="absolute -top-8 -right-8 opacity-30 pointer-events-none"><RadarSweep size={140} /></div>
          <div className="divide-y divide-emerald-900/50 relative">
            {entries.map((e, i) => {
              const ev = eventById[e.eventId];
              const color = AGENCY_COLORS[ev?.agency] || "#7CFFB2";
              const badge = SOURCE_BADGE[e.source];
              return (
                <div key={`${e.eventId}-${e.page}`}
                  className="px-3 py-2 hover:bg-emerald-900/20 cursor-pointer flex gap-3 items-start"
                  onClick={() => ev && onSelect?.(ev)}>
                  <div className="font-mono text-[9px] tracking-widest text-emerald-700 w-14 pt-0.5">
                    <span className="text-amber-400">{TIME_AGO(e.modifiedAt)}</span> ago
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-baseline gap-2 flex-wrap">
                      <span className="font-mono text-[9px] tracking-widest" style={{ color: badge.color }} title={badge.note}>
                        ▌ {badge.label}
                      </span>
                      <span className="font-mono text-[10px] text-emerald-700">PAGE {e.page}</span>
                      <span className="font-mono text-[10px] text-emerald-700">{e.chars}c</span>
                      {ev && (
                        <>
                          <span className="font-mono text-[9px] tracking-wider" style={{ color }}>
                            {ev.agency?.replace("Department of ", "DEPT/")}
                          </span>
                          <span className="font-mono text-[9px] text-amber-300">{e.date}</span>
                        </>
                      )}
                    </div>
                    <div className="font-mono text-[11px] text-emerald-100 mt-0.5 leading-snug truncate">
                      {e.title || e.eventId}
                    </div>
                    {e.snippet && (
                      <div className="font-mono text-[10px] text-emerald-500 mt-1 line-clamp-2 italic">
                        “{e.snippet}”
                      </div>
                    )}
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}

      <div className="mt-4 font-mono text-[10px] text-emerald-700 text-center tracking-wider">
        ▌ FEED IS REGENERATED ON EACH DEPLOY · CONTRIBUTORS WELCOME — SEE THE BUTTON ABOVE
      </div>
    </div>
  );
}
